// if("0"){
//     console.log('hello');
// }
// ////hello chiqadi

////////////
// let result;
// let a = 1,
//   b = 5;

// if (a + b < 4) {
//   result = "Below";
// } else {
//   result = "Over";
// }
// console.log(result);

//////
// let result;
// let a = 1,
//   b = 2;

// a + b < 4 ? console.log((result = "Below")) : console.log((result = "Over"));

/////////

// let message;
// let login;

// if (login == "Employee") {
//   message = "Hello";
// } else if (login == "Director") {
//   message = "Greetings";
// } else if (login == "") {
//   message = "No Login";
// } else {
//   message = "";
// }
// console.log(message);

////////////////

// let message;
// let login;

// login == "Employee"
//   ? console.log((message = "Hello"))
//   : login == "Director"
//   ? console.log((message = "Greetings"))
//   : login == ""
//   ? console.log((message = "No Login"))
//   : console.log((message = ""));

///////////////////////////// if else

// let a = 1,
//   b = 5;

// if(a>b){
//     console.log(`eng katta son : ${a} `);
// }else{
//     console.log(`eng katta son : ${b} `);
// }

///////////////////

// let num = Math.round(Math.random() * 100);  ////100gacha bolgan sonlardir agar oldiga -qoysak manfiy boladi
// console.log(num);////bunda qaysi son chiqayotganini aniqlash uchundir

// if(num>=0){
//     console.log(`bu son musbat son : ${num}`);
// }else{
//     console.log(`bu son manfiy son : ${num}`);
// }

// if (num % 2 == 0) {
//   console.log(`bu son juft son : ${num}`);
// } else {
//   console.log(`bu son toq son : ${num}`);
// }

// let a = Math.round(Math.random() * -10);
// let b = Math.round(Math.random() * 10);
// let c = Math.round(Math.random() * 10);

// if(a>0){
//     console.log(`musbat son : ${a}`);
// }else if(a<0){
//     console.log(`manfiy son : ${a}`);
// }else if(b>0){
//     console.log(`musbat son : ${b}`);
// }else if(b<0){
//     console.log(`manfiy son : ${b}`);
// }else if(c>0){
//     console.log(`musbat son : ${c}`);
// }else if(c<0){
//     console.log(`manfiy son : ${c}`);
// }

//////////////

// let a = Math.round(Math.random() * 10);
// let b = Math.round(Math.random() * 10);

// if (a<b){
//     console.log(1);
// }else {
//     console.log(2);
// }

// a > b ? console.log(2) : console.log(1);

// let a = Math.round(Math.random() * 10);
// let b = Math.round(Math.random() * 10);

// if (a<b){
//     console.log(`${b} \n  ${a}`);
// }else {
//     console.log(`${a} \n ${b}`);
// }

// a > b ? console.log(`${a}  =>  ${b}`) : console.log(`${b}  =>    ${a}`);

////////////

// let a = Math.round(Math.random() * 10);
// let b = Math.round(Math.random() * 10);

// console.log(`1chi son : ${a}`);
// console.log(`2chi son : ${b}`);

// if (a, b){
//     a=a+b;
//     b=a-b;
//     a=a-b;
// }

// console.log(a);
// console.log(b);

//////////////////////////////
// (a , b) ? a=a+b,
//  b=a-b,
//  a=a-b
//  : a=a;

//////
// let n = 100
// let c = 0;

// for (let i = 1; i <= n; i++) {
//   for (let j = 2; j <= i; j++) {
//     if (i % j == 0) {
//       c++;
//     }
//   }
//   if (c == 2) {
//     console.log(` tub son : ${i}`);
//   }
//  else {
//     console.log(`tub son emas : ${i}`);
//   }
//   c = 0;
}